name: release
on:
  push:

jobs:
  build:
    uses: cloud-cli/workflows/.github/workflows/npm-build-release.yml@main
    with:
      path: 'node'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}